const FIELDS = [
  { name: "product_name", label: "Nom du produit", type: "text" },
  { name: "energy-kj_100g", label: "Énergie (kJ)", type: "number", min: 0, max: 4000 },
  { name: "energy-kcal_100g", label: "Énergie (kcal)", type: "number", min: 0, max: 1000 },
  { name: "fat_100g", label: "Matières grasses (g)", type: "number", min: 0, max: 50 },
  { name: "saturated-fat_100g", label: "Gras saturés (g)", type: "number", min: 0, max: 30 },
  { name: "unsaturated-fat_100g", label: "Gras insaturés (g)", type: "number", min: 0, max: 40 },
  { name: "omega-3-fat_100g", label: "Oméga 3 (g)", type: "number", min: 0, max: 5 },
  { name: "sugars_100g", label: "Sucres (g)", type: "number", min: 0, max: 70 },
  { name: "added-sugars_100g", label: "Sucres ajoutés (g)", type: "number", min: 0, max: 40 },
  { name: "fiber_100g", label: "Fibres (g)", type: "number", min: 0, max: 20 },
  { name: "proteins_100g", label: "Protéines (g)", type: "number", min: 0, max: 30 },
  { name: "salt_100g", label: "Sel (g)", type: "number", min: 0, max: 3 },
  { name: "cholesterol_100g", label: "Cholestérol (mg)", type: "number", min: 0, max: 300 },
  { name: "vitamin-a_100g", label: "Vitamine A (µg)", type: "number", min: 0, max: 1000 },
  { name: "vitamin-c_100g", label: "Vitamine C (mg)", type: "number", min: 0, max: 200 },
  { name: "vitamin-d_100g", label: "Vitamine D (µg)", type: "number", min: 0, max: 20 },
  { name: "calcium_100g", label: "Calcium (mg)", type: "number", min: 0, max: 1200 },
  { name: "magnesium_100g", label: "Magnésium (mg)", type: "number", min: 0, max: 600 },
  { name: "zinc_100g", label: "Zinc (mg)", type: "number", min: 0, max: 15 },
  { name: "manganese_100g", label: "Manganèse (mg)", type: "number", min: 0, max: 5 },
  { name: "caffeine_100g", label: "Caféine (mg)", type: "number", min: 0, max: 200 },
  { name: "alcohol_100g", label: "Alcool (g)", type: "number", min: 0, max: 40 },
];
export default FIELDS;