FROM node:18-alpine as builder
 
WORKDIR /app

COPY front/package*.json ./
RUN npm ci

COPY front /app


RUN npm run build

# Prod
FROM nginx:stable-alpine
COPY --from=builder /app/build /usr/share/nginx/html


EXPOSE 80


CMD ["nginx", "-g", "daemon off;"]